In [1]:
load_model = 'efficientnet_based_model2.pt'

data_dir = '../../../stanford_dogs_new/'

In [2]:
# import numpy as np

from IPython.display import Image

import os
import torch
from torch import nn
from torch.utils.data import DataLoader
import torchvision.models as models
from torchvision import datasets, transforms
from torchvision.transforms import ToTensor

from torchvision.datasets import ImageFolder
from PIL import Image

from torch.autograd import Variable

from torch.optim import lr_scheduler
import numpy as np
import torchvision
from torchvision import datasets, models, transforms
import matplotlib.pyplot as plt
import time
import os
import copy


from IPython.display import Image
from IPython.display import Markdown

from PIL import Image
import PIL.Image

import pandas as pd

# sklearn metrics
from sklearn import metrics
from sklearn.metrics import cohen_kappa_score
from sklearn.metrics import f1_score


## load the efficientnet_widese_b0 based model

In [3]:
efficientnet_widese_b0_loaded = torch.hub.load('NVIDIA/DeepLearningExamples:torchhub', 'nvidia_efficientnet_b0', pretrained=True)

for param in efficientnet_widese_b0_loaded.parameters():
    param.requires_grad = True

efficientnet_widese_b0_loaded.fc = nn.Linear(in_features=1280, out_features=120, bias=True)

device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
efficientnet_widese_b0_loaded = efficientnet_widese_b0_loaded.to(device)



efficientnet_widese_b0_loaded.load_state_dict(torch.load('efficientnet_widese_b0_based_model2.pt'))
efficientnet_widese_b0_loaded.eval()

Downloading: "https://github.com/NVIDIA/DeepLearningExamples/archive/torchhub.zip" to /home/rka73/.cache/torch/hub/torchhub.zip
/home/rka73/.cache/torch/hub/NVIDIA_DeepLearningExamples_torchhub/PyTorch/Classification/ConvNets/image_classification/models/common.py:13: UserWarning: pytorch_quantization module not found, quantization will not be available
  warnings.warn(
/home/rka73/.cache/torch/hub/NVIDIA_DeepLearningExamples_torchhub/PyTorch/Classification/ConvNets/image_classification/models/efficientnet.py:17: UserWarning: pytorch_quantization module not found, quantization will not be available
  warnings.warn(
Downloading: "https://api.ngc.nvidia.com/v2/models/nvidia/efficientnet_b0_pyt_amp/versions/20.12.0/files/nvidia_efficientnet-b0_210412.pth" to /home/rka73/.cache/torch/hub/checkpoints/nvidia_efficientnet-b0_210412.pth


EfficientNet(
  (stem): Sequential(
    (conv): Conv2d(3, 32, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False)
    (bn): BatchNorm2d(32, eps=0.001, momentum=0.010000000000000009, affine=True, track_running_stats=True)
    (activation): SiLU(inplace=True)
  )
  (layers): Sequential(
    (0): Sequential(
      (block0): MBConvBlock(
        (depsep): Sequential(
          (conv): Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=32, bias=False)
          (bn): BatchNorm2d(32, eps=0.001, momentum=0.010000000000000009, affine=True, track_running_stats=True)
          (act): SiLU(inplace=True)
        )
        (se): SequentialSqueezeAndExcitation(
          (squeeze): Linear(in_features=32, out_features=8, bias=True)
          (expand): Linear(in_features=8, out_features=32, bias=True)
          (activation): SiLU(inplace=True)
          (sigmoid): Sigmoid()
          (mul_a_quantizer): Identity()
          (mul_b_quantizer): Identity()
        )
      

In [4]:
model = efficientnet_widese_b0_loaded

In [5]:
# preprocess the image for the model
preprocess = transforms.Compose([
    transforms.Resize(256),
    transforms.CenterCrop(224),
    transforms.ToTensor(),
    transforms.Normalize(
            mean=[0.485, 0.456, 0.406],
            std=[0.229, 0.224, 0.225]
    )
])

In [6]:
path = '../../../stanford_dogs_new/test'

list_subfolders_with_paths = [f.path for f in os.scandir(path) if f.is_dir()]

# gets the breed name from subfolders name like 'n02099429-curly-coated_retriever'
def rename(name):
    return ' '.join(' '.join(name.split('-')[1:]).split('_'))

per_class_accuracy = dict()
total_accuracy = 0

y_true = []
y_pred = []

for breed_dir in list_subfolders_with_paths:
    
    breed = rename(breed_dir.split('/')[-1])
    
    images = os.listdir(breed_dir)
    
    matched = False
    matches = 0
    total_images = len(images)

    for image in images:

        input_image = Image.open(breed_dir + '/' + image)


        input_tensor = preprocess(input_image)
        if torch.cuda.is_available():
            input_tensor = Variable(input_tensor.cuda())

        input_batch = input_tensor.unsqueeze(0)
        out = model(input_batch)

        probabilities = torch.nn.functional.softmax(out[0], dim=0)
        # print(probabilities)

        with open("../../stanford_dogs_breeds_classes_final.txt", "r") as f:
            categories = [s.strip() for s in f.readlines()]

        predicted_breeds = []
        top1_prob, top1_catid = torch.topk(probabilities, 1)
        for i in range(top1_prob.size(0)):
            # predicted_breeds.append([categories[top3_catid[i]], top3_prob[i].item()*100])
            predicted_breed = categories[top1_catid[i]]
            y_true.append(breed)
            y_pred.append(predicted_breed)

        # list to be used directly by the application (predicted_breed, probability)
        # print("predicted_breeds are: \n", predicted_breed)
        if breed == predicted_breed:
            matched = True
            matches = matches + 1

        per_class_accuracy[breed] = matches / total_images * 100

In [7]:
df = pd.DataFrame(list(zip(y_true, y_pred)),
               columns =['Actual_breed', 'Predicted_breed'])

df

Actual_breed Predicted_breed
0      Pomeranian      Pomeranian
1      Pomeranian      Pomeranian
2      Pomeranian      Pomeranian
3      Pomeranian      Pomeranian
4      Pomeranian      Pomeranian
...           ...             ...
2105     papillon        papillon
2106     papillon        papillon
2107     papillon        papillon
2108     papillon        papillon
2109     papillon        papillon

[2110 rows x 2 columns]

## Confusion Matrix

In [8]:
# Print the confusion matrix
print(metrics.confusion_matrix(y_true, y_pred))


[[23  0  0 ...  0  0  0]
 [ 0 17  0 ...  0  0  0]
 [ 0  0 19 ...  0  0  1]
 ...
 [ 0  0  0 ... 14  0  0]
 [ 0  0  0 ...  0 11  0]
 [ 0  0  0 ...  0  0 10]]


## Precision, Recall and F1

In [9]:
# Print the precision and recall, among other metrics
print(metrics.classification_report(y_true, y_pred, digits=3))

                                precision    recall  f1-score   support

                  Afghan hound      0.852     0.958     0.902        24
           African hunting dog      0.944     1.000     0.971        17
                      Airedale      0.760     0.905     0.826        21
American Staffordshire terrier      0.615     0.471     0.533        17
                   Appenzeller      0.714     0.312     0.435        16
            Australian terrier      1.000     0.750     0.857        20
            Bedlington terrier      0.900     0.947     0.923        19
          Bernese mountain dog      0.750     0.955     0.840        22
              Blenheim spaniel      0.947     0.947     0.947        19
                 Border collie      0.643     0.600     0.621        15
                Border terrier      0.773     0.944     0.850        18
                   Boston bull      0.783     0.947     0.857        19
          Bouvier des Flandres      0.800     0.800     0.800  

## Macro F1 Score

In [10]:
from sklearn.metrics import f1_score

f1_score(y_true, y_pred, average='macro')


0.7482062904916683

## Micro F1 Score

In [11]:
f1_score(y_true, y_pred, average='micro')


0.7592417061611374

## Weighted F1 Score

In [12]:
f1_score(y_true, y_pred, average='weighted')

0.7526754212310284

## Cohen Kappa Score

In [13]:
from sklearn.metrics import cohen_kappa_score

cohen_kappa_score(y_true, y_pred)

0.7571665412339768

## Total Accuracy calculated from per class accuracy

In [14]:
# calculated from per class accuracy
total_accuracy = sum(per_class_accuracy.values())/120
total_accuracy

75.25346209876008

## Per Breed Accuracy

### Top 10 Breeds with least accuracy

In [15]:
k = 10
sorted(per_class_accuracy.items(), key=lambda x: x[1])[:k]

[('Walker hound', 18.75),
 ('collie', 18.75),
 ('Eskimo dog', 26.666666666666668),
 ('Appenzeller', 31.25),
 ('standard schnauzer', 31.25),
 ('giant schnauzer', 37.5),
 ('Lhasa', 42.10526315789473),
 ('miniature poodle', 43.75),
 ('Cardigan', 43.75),
 ('American Staffordshire terrier', 47.05882352941176)]

### Top 10 Breeds with most accuracy

In [16]:
k = 10
sorted(per_class_accuracy.items(), key=lambda x: x[1], reverse=True)[:k]

[('Pomeranian', 100.0),
 ('Irish setter', 100.0),
 ('komondor', 100.0),
 ('miniature schnauzer', 100.0),
 ('keeshond', 100.0),
 ('bloodhound', 100.0),
 ('Kerry blue terrier', 100.0),
 ('African hunting dog', 100.0),
 ('Afghan hound', 95.83333333333334),
 ('Bernese mountain dog', 95.45454545454545)]